import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log("sesssPrivateLayout=> ", session);
  if (!session) {
    redirect("/login");
  }

  return (
    <div className="private-layout">
      <Header username={session.user?.name} />
      {children}
    </div>
  );
}
